
version: '3'
networks:
  springcloud-overlay:
    external:
      name: springcloud-overlay
services:
  config-server:
    image: config-server
    build: congif-server
    ports:
      - 8089:8089

  eureka-naming-server:
    image: eureka-naming-server
    build: eureka-naming-server
    ports:
      - 8761:8761

  zuul-api-gateway:
    image: zuul-api-gateway
    build: zuul-api-gateway
    ports:
      - 8765:8765
    depends_on:
      - eureka-naming-server
  #    environment:
  #      - EUREKA_SERVER_ADDRESS=eureka-naming-server
  #    links:
  #      - eureka-naming-server


  spring-boot-command-framework:
    image: command-framework
    build: command-framework
    ports:
      - 8080:8080
    depends_on:
      - eureka-naming-server

  command-registry-angular:
    image: command-registry-angular
    build: command-registry-angular
    ports:
      - 8083:8083
    depends_on:
      - eureka-naming-server


  spring-boot-command-registry:
    image: helpdesk_project_spring-boot-command-framework
    build: command-registry
    ports:
      - 8082:8082
    depends_on:
      - mongo-command
      - eureka-naming-server
    environment:
      mongo_url: mongodb://mongo-command/command

  csr-service:
    image: csr-service
    build: csr-service
    ports:
      - 8182:8182
    depends_on:
      - mongo-command

  mongo-command:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_DATA_DIR=/data/command
    ports:
      - 27017:27017
    volumes:
      - $HOME/workspace/productdb/command:/data/db